---
- name: Join worker nodes
  hosts: workers
  become: true
  gather_facts: false

  tasks:
    - name: Join cluster
      ansible.builtin.command: "{{ hostvars[groups['control_plane'][0]].worker_join_command }}"
      args:
        creates: /etc/kubernetes/kubelet.conf
