---
- name: Install AWS Load Balancer Controller and Metrics Server
  hosts: control_plane
  become: true
  gather_facts: false

  vars_files:
    - group_vars/all_lab.yml

  tasks:
    - name: Add AWS Load Balancer Controller Helm repository
      ansible.builtin.shell: |
        helm repo add eks https://aws.github.io/eks-charts
        helm repo update
      changed_when: true

    - name: Install AWS Load Balancer Controller
      ansible.builtin.shell: |
        helm upgrade --install aws-load-balancer-controller \
          eks/aws-load-balancer-controller \
          --namespace kube-system \
          --set clusterName={{ cluster_name }} \
          --set region={{ aws_region }} \
          --set vpcId={{ vpc_id }} \
          --set nodeSelector."node-role\.kubernetes\.io/control-plane"="" \
          --set tolerations[0].key=node-role.kubernetes.io/control-plane \
          --set tolerations[0].operator=Exists \
          --set tolerations[0].effect=NoSchedule
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      changed_when: true

    - name: Wait for controller
      ansible.builtin.shell: |
        kubectl scale  deployment/aws-load-balancer-controller -n kube-system --replicas=1
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      changed_when: false

    - name: Show controller pods
      ansible.builtin.shell: |
        kubectl get pods -n kube-system \
          -l app.kubernetes.io/name=aws-load-balancer-controller \
          -o wide
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      changed_when: false
      register: controller_status

    - name: Display controller status
      ansible.builtin.debug:
        var: controller_status.stdout_lines

    - name: Copy Metrics Server manifest
      ansible.builtin.copy:
        src: metrics-server.yaml
        dest: /home/{{ ansible_user }}/metrics-server.yaml
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0644'

    - name: Install Metrics Server
      ansible.builtin.command:
        cmd: kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f /home/{{ ansible_user }}/metrics-server.yaml     

    - name: Show Metrics Server pods
      ansible.builtin.shell: |
        kubectl get pods -n kube-system \
          -l k8s-app=metrics-server \
          -o wide
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      changed_when: false
      register: metrics_server_status

    - name: Display Metrics Server status
      ansible.builtin.debug:
        var: metrics_server_status.stdout_lines        

    - name: Copy kubernetes directory to control plane node
      ansible.builtin.copy:
        src: ../kubernetes/
        dest: /home/{{ ansible_user }}/kubernetes/
